# Generated by Django 5.0.4 on 2024-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bid_username_remove_comment_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.CharField(default=False, max_length=64),
            preserve_default=False,
        ),
    ]
