# Generated by Django 5.0.4 on 2024-05-22 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='username',
        ),
    ]
