# Generated by Django 5.0.4 on 2024-05-22 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_listing_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='username',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
